[tool.poetry]
name = "learn-ai"
version = "0.1.0"
description = ""
authors = ["Kyle Getrost <kyle@motionhungry.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
replicate = "^0.33.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
